// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbsjcsqxbhmfujxdjrfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpic2pjc3F4YmhtZnVqeGRqcmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTUyNzgsImV4cCI6MjA3MTE3MTI3OH0.L0cKxkx8TgNUaHua0k3TzVj34J2_mjOJ0WTQtRH7kqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});